In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/my_file (1).csv")

In [ ]:
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [ ]:
print(df.isnull().sum())

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [ ]:
clean = df.dropna()
cleaned = clean.reset_index(drop=True)

In [ ]:
print("\nCleaned Dataset:")
print(cleaned)

Cleaned Dataset:
   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
4     6  2[4]         10[9]  $305,158,363                     $388,978,496

         Artist                   Tour title    Year(s)  Shows Average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4       Madonna                The MDNA Tour       2012     88    $3,467,709

  Ref.
0  [1]
1  [3]
2  [6]
3  [7]
4  [9]

In [ ]:
clean

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]

QUESTION 1

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
print("Original Dataset:")
print(df.head())
df = df.dropna()
df = df.drop_duplicates()
df.columns = df.columns.str.upper()
print("\nCleaned Dataset:")
print(df.head())

Original Dataset:
   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
4     5  2[4]           NaN  $345,675,146                     $402,844,849

         Artist                   Tour title    Year(s)  Shows Average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4  Taylor Swift      Reputation Stadium Tour       2018     53    $6,522,173

  Ref.
0  [1]
1  [3]
2  [6]
3  [7]
4  [8]

Cleaned Dataset:
   RANK  PEAK ALL TIME PEAK  ACTUAL GROSS ADJUSTED GROSS (IN 2022 DOLLARS)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
5     6  2[4]         10[9]  $305,158,363                     $388,978,496

         ARTIST                   TOUR TITLE    YEAR(S)  SHOWS AVERAGE GROSS  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
5       Madonna                The MDNA Tour       2012     88    $3,467,709

  REF.
0  [1]
1  [3]
2  [6]
3  [7]
5  [9]

QUESTION 2

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())
print(df.columns)

   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
4     5  2[4]           NaN  $345,675,146                     $402,844,849

         Artist                   Tour title    Year(s)  Shows Average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4  Taylor Swift      Reputation Stadium Tour       2018     53    $6,522,173

  Ref.
0  [1]
1  [3]
2  [6]
3  [7]
4  [8]
    Rank Peak All Time Peak     Actual gross Adjusted gross (in 2022 dollars)  \
15    16  NaN           NaN     $184,000,000                     $227,452,347
16    17  NaN           NaN     $170,000,000                     $213,568,571
17    18  NaN           NaN     $169,800,000                     $207,046,755
18    19  NaN           NaN  $167,700,000[e]                     $204,486,106
19    20  NaN           NaN     $150,000,000                     $185,423,109

          Artist                 Tour title    Year(s)  Shows Average gross  \
15          Pink  The Truth About Love Tour  2013–2014    142    $1,295,775
16     Lady Gaga         Born This Way Ball  2012–2013     98    $1,734,694
17       Madonna           Rebel Heart Tour  2015–2016     82    $2,070,732
18         Adele            Adele Live 2016  2016–2017    121    $1,385,950
19  Taylor Swift               The Red Tour  2013–2014     86    $1,744,186

    Ref.
15  [22]
16   [d]
17   [4]
18  [25]
19  [26]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB
None
            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000
Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='object')

QUESTION 3

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
print(df.isnull().sum())
df = df.fillna("Unknown")
print(df.isnull().sum())

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64
Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

QUESTION 4

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
print("Duplicate Rows:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicates Removed")

Duplicate Rows: 0
Duplicates Removed

QUESTION 5

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
df = df.drop_duplicates()
df = df.fillna("Unknown")
df.columns = df.columns.str.lower()
print(df.head())

   rank  peak all time peak  actual gross adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
4     5  2[4]       Unknown  $345,675,146                     $402,844,849

         artist                   tour title    year(s)  shows average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4  Taylor Swift      Reputation Stadium Tour       2018     53    $6,522,173

  ref.
0  [1]
1  [3]
2  [6]
3  [7]
4  [8]

QUESTION 6

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
df["Peak"] = pd.to_numeric(df["Peak"], errors="coerce")
df = df.dropna(subset=["Peak"])
filtered = df[df["Peak"] > 10]
print(filtered)

Empty DataFrame
Columns: [Rank, Peak, All Time Peak, Actual gross, Adjusted gross (in 2022 dollars), Artist, Tour title, Year(s), Shows, Average gross, Ref.]
Index: []

QUESTION 7

In [ ]:
# List
numbers = [10,20,30]
numbers.append(40)
print(numbers)
# Tuple
t = (1,2,3)
print(t)
# Dictionary
student = {"Name":"John","Age":20}
print(student)
# Set
s = {1,2,2,3,4}
print(s)

[10, 20, 30, 40]
(1, 2, 3)
{'Name': 'John', 'Age': 20}
{1, 2, 3, 4}

QUESTION 8

In [ ]:
a = 20
b = 10
print("Addition =", a+b)
if a>b:
    print("A is Greater")
else:
    print("B is Greater")
for i in range(5):
    print(i)
def square(x):
    return x*x
print(square(6))

Addition = 30
A is Greater
0
1
2
3
4
36

QUESTION 9

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
print(df.head())
print("Rows:", len(df))
print("Columns:", len(df.columns))

   Rank  Peak All Time Peak  Actual gross Adjusted gross (in 2022 dollars)  \
0     1     1             2  $780,000,000                     $780,000,000
1     2     1          7[2]  $579,800,000                     $579,800,000
2     3  1[4]          2[5]  $411,000,000                     $560,622,615
3     4  2[7]         10[7]  $397,300,000                     $454,751,555
4     5  2[4]           NaN  $345,675,146                     $402,844,849

         Artist                   Tour title    Year(s)  Shows Average gross  \
0  Taylor Swift              The Eras Tour †  2023–2024     56   $13,928,571
1       Beyoncé       Renaissance World Tour       2023     56   $10,353,571
2       Madonna  Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3          Pink  Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4  Taylor Swift      Reputation Stadium Tour       2018     53    $6,522,173

  Ref.
0  [1]
1  [3]
2  [6]
3  [7]
4  [8]
Rows: 20
Columns: 11

QUESTION 10

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
df.to_json("sample.json", orient="records", indent=4)
print("sample.json created successfully!")

sample.json created successfully!

QUESTION 11

In [ ]:
xml_data = """<?xml version="1.0" encoding="UTF-8"?>
<students>
    <student>
        <name>John</name>
        <age>20</age>
    </student>
    <student>
        <name>Alice</name>
        <age>22</age>
    </student>
    <student>
        <name>Bob</name>
        <age>21</age>
    </student>
</students>
"""
with open("sample.xml", "w") as file:
    file.write(xml_data)
print("sample.xml created successfully!")

sample.xml created successfully!

QUESTION 11

In [ ]:
import pandas as pd

df = pd.read_xml("sample.xml")

print(df)

    name  age
0   John   20
1  Alice   22
2    Bob   21

QUESTION 12

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
df.to_json("output.json", orient="records", indent=4)
print("Converted Successfully")

Converted Successfully

QUESTION 13

In [ ]:
import pandas as pd
df = pd.read_json("sample.json")
df.to_csv("output.csv", index=False)
print("Converted Successfully")

Converted Successfully

QUESTION 14

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
mid = len(df) // 2
df1 = df.iloc[:mid]
df2 = df.iloc[mid:]
df1.to_csv("file1.csv", index=False)
df2.to_csv("file2.csv", index=False)
print("file1.csv and file2.csv created successfully!")

file1.csv and file2.csv created successfully!

QUESTION 15

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
print(df.isnull().sum())
print(df[df.duplicated()])

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64
Empty DataFrame
Columns: [Rank, Peak, All Time Peak, Actual gross, Adjusted gross (in 2022 dollars), Artist, Tour title, Year(s), Shows, Average gross, Ref.]
Index: []

QUESTION 16

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
# Rename
df.rename(columns={"Peak":"HighestPeak"}, inplace=True)
# Add
df["NewColumn"] = 100
# Delete
df.drop(columns=["NewColumn"], inplace=True)
print(df.head())

   Rank HighestPeak All Time Peak  Actual gross  \
0     1           1             2  $780,000,000
1     2           1          7[2]  $579,800,000
2     3        1[4]          2[5]  $411,000,000
3     4        2[7]         10[7]  $397,300,000
4     5        2[4]           NaN  $345,675,146

  Adjusted gross (in 2022 dollars)        Artist                   Tour title  \
0                     $780,000,000  Taylor Swift              The Eras Tour †
1                     $579,800,000       Beyoncé       Renaissance World Tour
2                     $560,622,615       Madonna  Sticky & Sweet Tour ‡[4][a]
3                     $454,751,555          Pink  Beautiful Trauma World Tour
4                     $402,844,849  Taylor Swift      Reputation Stadium Tour

     Year(s)  Shows Average gross Ref.
0  2023–2024     56   $13,928,571  [1]
1       2023     56   $10,353,571  [3]
2  2008–2009     85    $4,835,294  [6]
3  2018–2019    156    $2,546,795  [7]
4       2018     53    $6,522,173  [8]

QUESTION 17

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
# Convert Peak to numeric
df["Peak"] = pd.to_numeric(df["Peak"], errors="coerce")
# Remove rows where Peak is missing
df = df.dropna(subset=["Peak"])
# Group by Artist and calculate average Peak
result = df.groupby("Artist")["Peak"].mean()
print(result)

Artist
Beyoncé         1.0
Taylor Swift    1.0
Name: Peak, dtype: float64

QUESTION 18

In [ ]:
import pandas as pd
df = pd.read_csv("/content/my_file (1).csv")
df.to_csv("output.csv", index=False)
df.to_json("output.json", orient="records")
df.to_excel("output.xlsx", index=False)
print("Exported Successfully")

Exported Successfully

QUESTION 19

In [ ]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("sample.db")
df = pd.read_csv("/content/my_file (1).csv")
df.to_sql("songs", conn, if_exists="replace", index=False)
print(pd.read_sql("SELECT * FROM songs", conn))
print(pd.read_sql("PRAGMA table_info(songs)", conn))
conn.close()

    Rank   Peak All Time Peak     Actual gross  \
0      1      1             2     $780,000,000
1      2      1          7[2]     $579,800,000
2      3   1[4]          2[5]     $411,000,000
3      4   2[7]         10[7]     $397,300,000
4      5   2[4]          None     $345,675,146
5      6   2[4]         10[9]     $305,158,363
6      7  2[10]          None     $280,000,000
7      7   None          None     $257,600,000
8      9   None          None     $256,084,556
9     10   None          None     $250,400,000
10    11   None          None  $229,100,000[b]
11    12   None        14[17]     $227,400,000
12    13   None          None     $204,000,000
13    14  1[20]          None     $200,000,000
14    15   2[c]          None     $194,000,000
15    16   None          None     $184,000,000
16    17   None          None     $170,000,000
17    18   None          None     $169,800,000
18    19   None          None  $167,700,000[e]
19    20   None          None     $150,000,000

   Adjusted gross (in 2022 dollars)        Artist  \
0                      $780,000,000  Taylor Swift
1                      $579,800,000       Beyoncé
2                      $560,622,615       Madonna
3                      $454,751,555          Pink
4                      $402,844,849  Taylor Swift
5                      $388,978,496       Madonna
6                      $381,932,682   Celine Dion
7                      $257,600,000          Pink
8                      $312,258,401       Beyoncé
9                      $309,141,878  Taylor Swift
10                     $283,202,896       Beyoncé
11                     $295,301,479     Lady Gaga
12                     $251,856,802    Katy Perry
13                     $299,676,265          Cher
14                     $281,617,035       Madonna
15                     $227,452,347          Pink
16                     $213,568,571     Lady Gaga
17                     $207,046,755       Madonna
18                     $204,486,106         Adele
19                     $185,423,109  Taylor Swift

                                  Tour title    Year(s)  Shows Average gross  \
0                            The Eras Tour †  2023–2024     56   $13,928,571
1                     Renaissance World Tour       2023     56   $10,353,571
2                Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3                Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4                    Reputation Stadium Tour       2018     53    $6,522,173
5                              The MDNA Tour       2012     88    $3,467,709
6                  Taking Chances World Tour  2008–2009    131    $2,137,405
7                          Summer Carnival †  2023–2024     41    $6,282,927
8                   The Formation World Tour       2016     49    $5,226,215
9                        The 1989 World Tour       2015     85    $2,945,882
10           The Mrs. Carter Show World Tour  2013–2014    132    $1,735,606
11                   The Monster Ball Tour *  2009–2011    203    $1,118,227
12                      Prismatic World Tour  2014–2015    151    $1,350,993
13  Living Proof: The Farewell Tour ‡[21][a]  2002–2005    325      $615,385
14                          Confessions Tour       2006     60    $3,233,333
15                 The Truth About Love Tour  2013–2014    142    $1,295,775
16                        Born This Way Ball  2012–2013     98    $1,734,694
17                          Rebel Heart Tour  2015–2016     82    $2,070,732
18                           Adele Live 2016  2016–2017    121    $1,385,950
19                              The Red Tour  2013–2014     86    $1,744,186

        Ref.
0        [1]
1        [3]
2        [6]
3        [7]
4        [8]
5        [9]
6       [11]
7       [12]
8       [13]
9       [14]
10  [15][16]
11      [18]
12      [19]
13      [20]
14       [5]
15      [22]
16       [d]
17       [4]
18      [25]
19      [26]
    cid                              name     type  notnull dflt_value  pk
0     0                              Rank  INTEGER        0       None   0
1     1                              Peak     TEXT        0       None   0
2     2                     All Time Peak     TEXT        0       None   0
3     3                      Actual gross     TEXT        0       None   0
4     4  Adjusted gross (in 2022 dollars)     TEXT        0       None   0
5     5                            Artist     TEXT        0       None   0
6     6                        Tour title     TEXT        0       None   0
7     7                           Year(s)     TEXT        0       None   0
8     8                             Shows  INTEGER        0       None   0
9     9                     Average gross     TEXT        0       None   0
10   10                              Ref.     TEXT        0       None   0

QUESTION 20

In [ ]:
import pandas as pd
# Import
df = pd.read_csv("/content/my_file (1).csv")
# Cleaning
df = df.drop_duplicates()
df = df.fillna("Unknown")
# Validation
print(df.isnull().sum())
# Transformation
df.columns = df.columns.str.upper()
# Export
df.to_csv("final.csv", index=False)
df.to_json("final.json", orient="records")
df.to_excel("final.xlsx", index=False)
print("Data Wrangling Completed Successfully")

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64
Data Wrangling Completed Successfully

In [ ]:
import mysql.connector
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="mydatabase"
)
cur = conn.cursor()
cur.commit()
CREATE TABLE Students

20-06-2026

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/dup.csv")
print("ASAL")
print(df)
d = df.drop_duplicates()
print("FAKE")
print(d)

ASAL
   CustomerID          Name                   Email       Phone
0           1  Rohit Sharma  rohit.sharma@email.com  9876543210
1           2  Anjali Gupta  anjali.gupta@email.com  9876543211
2           3  Manoj Tiwari  manoj.tiwari@email.com  9876543212
3           1  Rohit Sharma  rohit.sharma@email.com  9876543210
4           4    Kavita Rao    kavita.rao@email.com  9876543213
5           2  Anjali Gupta  anjali.gupta@email.com  9876543211
6           5  Deepak Joshi  deepak.joshi@email.com  9876543214
7           6  Sunita Reddy  sunita.reddy@email.com  9876543215
8           3  Manoj Tiwari  manoj.tiwari@email.com  9876543212
9           7    Farhan Ali    farhan.ali@email.com  9876543216
FAKE
   CustomerID          Name                   Email       Phone
0           1  Rohit Sharma  rohit.sharma@email.com  9876543210
1           2  Anjali Gupta  anjali.gupta@email.com  9876543211
2           3  Manoj Tiwari  manoj.tiwari@email.com  9876543212
4           4    Kavita Rao    kavita.rao@email.com  9876543213
6           5  Deepak Joshi  deepak.joshi@email.com  9876543214
7           6  Sunita Reddy  sunita.reddy@email.com  9876543215
9           7    Farhan Ali    farhan.ali@email.com  9876543216

# LAB PROGRAMS

QUESTION 1

In [ ]:
import pandas as pd
from google.colab import files

# Upload the CSV file
uploaded = files.upload()

# Read the uploaded file
df = pd.read_csv("departments.csv")

# Display distinct department IDs
print("Distinct Department IDs:")
print(df["DEPARTMENT_ID"].unique())

Saving departments.csv to departments.csv
Distinct Department IDs:
[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270]

QUESTION 2

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("job_history.csv")

result = df.groupby("EMPLOYEE_ID").size()
result = result[result >= 2]

print("Employee IDs with two or more jobs:")
print(result.index.tolist())

Saving job_history.csv to job_history.csv
Employee IDs with two or more jobs:
[101, 176, 200]

QUESTION 3

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("jobs.csv")

result = df.sort_values(by="JOB_TITLE", ascending=False)

print(result)

Saving jobs.csv to jobs.csv
        JOB_ID                        JOB_TITLE  MIN_SALARY  MAX_SALARY
11      ST_MAN                    Stock Manager        5500        8500
12    ST_CLERK                      Stock Clerk        2008        5000
13    SH_CLERK                   Shipping Clerk        2500        5500
8       SA_REP             Sales Representative        6000       12008
7       SA_MAN                    Sales Manager       10000       20080
9       PU_MAN               Purchasing Manager        8000       15000
10    PU_CLERK                 Purchasing Clerk        2500        5500
18      PR_REP  Public Relations Representative        4500       10500
6   AC_ACCOUNT                Public Accountant        4200        9000
14     IT_PROG                       Programmer        4000       10000
0      AD_PRES                        President       20080       40000
16      MK_REP         Marketing Representative        4000        9000
15      MK_MAN                Marketing Manager        9000       15000
17      HR_REP   Human Resources Representative        4000        9000
3       FI_MGR                  Finance Manager        8200       16000
1        AD_VP    Administration Vice President       15000       30000
2      AD_ASST         Administration Assistant        3000        6000
5       AC_MGR               Accounting Manager        8200       16000
4   FI_ACCOUNT                       Accountant        4200        9000

# UNIT 3 SCENARIO BASED QUESTION

Q1

In [ ]:
import pandas as pd

# Sample raw data
data = {
    "Name": ["Alice", "Bob", None, "Charlie", "David"],
    "Age": [25, "Thirty", 29, None, 22],
    "Salary": [50000, 55000, 60000, 58000, "Sixty-Five Thousand"]
}

df = pd.DataFrame(data)

# Display raw data
print("Raw Data:")
print(df)

# Handling missing values and standardizing data formats
df["Name"].fillna("Unknown", inplace=True)
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")# Convert Age to numeric
df["Salary"] = df["Salary"].replace("Sixty-Five Thousand", 65000).astype(int)  # Fix salary format

# Display cleaned data
print("\nCleaned Data:")
print(df)

Raw Data:
      Name     Age               Salary
0    Alice      25                50000
1      Bob  Thirty                55000
2     None      29                60000
3  Charlie    None                58000
4    David      22  Sixty-Five Thousand

Cleaned Data:
      Name   Age  Salary
0    Alice  25.0   50000
1      Bob   NaN   55000
2  Unknown  29.0   60000
3  Charlie   NaN   58000
4    David  22.0   65000

/tmp/ipykernel_1425/2678620554.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)
/tmp/ipykernel_1425/2678620554.py:19: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Salary"] = df["Salary"].replace("Sixty-Five Thousand", 65000).astype(int)  # Fix salary format

Q2

In [ ]:
# Checking for missing values
print("Missing Values Count:")
print(df.isnull().sum())

# Identifying incorrect entries
print("\nData Types:")
print(df.dtypes)

Missing Values Count:
Name      0
Age       2
Salary    0
dtype: int64

Data Types:
Name       object
Age       float64
Salary      int64
dtype: object

Q3

In [ ]:
import pandas as pd

data = {
    "Date": ["2025-01-01", "01-02-2025", "2025/03/05", "15-04-2025"]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"], format="mixed", dayfirst=True)

print(df)

        Date
0 2025-01-01
1 2025-02-01
2 2025-03-05
3 2025-04-15

Q4

In [ ]:
import numpy as np

data = {'Sales': [200, 250, 300, 1500, 260, 270, 280, 10000]}
df = pd. DataFrame(data)

Q1 = np.percentile(df["Sales"], 25)
Q3 = np.percentile(df["Sales"], 75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["Sales"] < lower_bound) | (df["Sales"] > upper_bound)]
print("Outliers:")
print(outliers)

Outliers:
   Sales
3   1500
7  10000

Q5

In [ ]:
data = {'ID': [1, 2, 3, 2, 4, 5, 3], 'Value': [100, 200, 300, 200, 400, 500, 300]}
df = pd.DataFrame(data)

duplicates = df[df.duplicated()]
print("Duplicates Found:")
print(duplicates)

df_cleaned = df.drop_duplicates()
print("\nCleaned Data:")
print(df_cleaned)

Duplicates Found:
   ID  Value
3   2    200
6   3    300

Cleaned Data:
   ID  Value
0   1    100
1   2    200
2   3    300
4   4    400
5   5    500

Q6

In [ ]:
!pip install fuzzywuzzy
!pip install python-Levenshtein

from fuzzywuzzy import process

names = ["John Doe", "Jon Doe", "Jane Doe", "J0hn Doe"]
query = "John Doe"

matches = process.extract(query, names, limit=3)

print("Fuzzy Matches:")
print(matches)

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.12/dist-packages (0.18.0)
Requirement already satisfied: python-Levenshtein in /usr/local/lib/python3.12/dist-packages (0.27.3)
Requirement already satisfied: Levenshtein==0.27.3 in /usr/local/lib/python3.12/dist-packages (from python-Levenshtein) (0.27.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from Levenshtein==0.27.3->python-Levenshtein) (3.14.5)
Fuzzy Matches:
[('John Doe', 100), ('Jon Doe', 93), ('J0hn Doe', 88)]

Q7

In [ ]:
import re

emails = ["test@example.com", "user.name@domain.com", "invalid-email@", "hello@world"]

def is_valid_email(email):
    pattern = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    return bool (re.match(pattern, email))

invalid_emails = [email for email in emails if not is_valid_email(email)]
print("Invalid Emails:", invalid_emails)

Invalid Emails: ['invalid-email@', 'hello@world']

Q8

In [ ]:
from sklearn.preprocessing import MinMaxScaler

data = {'Value': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)


scaler = MinMaxScaler()
df["Normalized"] = scaler.fit_transform(df[["Value"]])

print(df)

   Value  Normalized
0    100        0.00
1    200        0.25
2    300        0.50
3    400        0.75
4    500        1.00

Q9

In [ ]:
df.to_csv("cleaned_data.csv", index=False)
print ("Data saved successfully.")

Data saved successfully.

Q10

In [ ]:
import pandas as pd

# Sample Data
data = {
    "Name": ["Alice", "Bob", None, "Charlie"],
    "Age": [25, "Thirty", 29, None]
}

df = pd.DataFrame(data)

# Function to clean data
def clean_data(df):
    df = df.fillna("Unknown")                 # Fill missing values
    df["Age"] = pd.to_numeric(df["Age"], errors="coerce")  # Convert Age to numeric
    return df

# Apply function
df = clean_data(df)

print(df)

      Name   Age
0    Alice  25.0
1      Bob   NaN
2  Unknown  29.0
3  Charlie   NaN